name: falcon
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - conda-forge::jupyterlab
  - matplotlib
  - seaborn
  - tensorflow-gpu
  - conda-forge::opencv
  - Pillow
  - PyYAML
  - requests
  - scipy
  - pytorch
  - torchvision
  - tqdm
  - tensorboard
